version: "3"
services:

   db:
     image: mongo:7.0
     volumes:
       - demo_db_data:/data/db
     restart: always
     networks:
       demonet:
         ipv4_address: 172.25.0.2

   project:
     depends_on:
       - db
     image: chunyiwang/autosell:2.0
     environment:
       DB_HOST: 172.25.0.2
       DB_PORT: 27017
       DB_NAME: SIT725Project
     volumes:
       - project_files:/SIT725_preowned_vehicles
     restart: always
     networks:
       demonet:
         ipv4_address: 172.25.0.3

volumes:
  demo_db_data:
  project_files: 

networks:
   demonet:
     ipam:
       config:
         - subnet: 172.25.0.0/24

